
[package]
authors = ["xingwangzhe"]
edition = "2021"
rust-version = "1.95"
name = "mermaid-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "3.6.9"
merman = { version = "=0.7.0", default-features = false, features = ["render"] }
serde_json = "1"

[dependencies.napi]
version = "3.13.0"
features = ["napi10"]

[build-dependencies]
napi-build = "2.5.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
incremental = false
strip = "symbols"

[patch.crates-io]
merman-core = { path = "vendor/merman-core" }
