/* auto-generated by NAPI-RS */
/* eslint-disable */

/** Synchronous SVG rendering via the published Merman Rust facade. */
export declare function render(code: string, opts?: RenderOptions | undefined | null): string;

/** Internal transport options. TypeScript translates legacy option names. */
export interface RenderOptions {
  siteConfigJson?: string;
  diagramId?: string;
  scopedCss?: string;
  fastTextMetrics?: boolean;
  viewportWidth?: number;
  viewportHeight?: number;
}

export declare function supportedDiagrams(): Array<string>;
